
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "Principles pf eating disorder",
    "url" : "http://fooddisorder.com",
    "author" : "Fat prof."
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "jrid",
    "name": "Joy rid",
    "password" : "secret"
}


###

GET http://localhost:3003/api/users